apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    server.servlet.context-path: /
    server.port: 8089
    server.error.include-message: always
    springdoc.packagesToScan: com.training.demo.controller
    springdoc.pathsToMatch: /**
    springdoc.swagger-ui.operationsSorter: method
    spring.datasource.url: jdbc:mysql://database-1.cbcf5nqqagbl.ap-south-1.rds.amazonaws.com:3306/labdb?prepareThreshold=0
    spring.datasource.username: admin
    spring.datasource.password: $PASSWORD