apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: myapp-container
      image: public.ecr.aws/d9g1d4w4/labs1:latest
      ports:
       - containerPort: 8089
      envFrom:
       - configMapRef:
          name: app-config
      env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
          secretKeyRef:
            name: mysql-db-password
            key: PASSWORD
        
  
